# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# OS, Python version, etc.
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

sphinx:
  configuration: conf.py

python:
  install:
  - requirements: requirements.txt
